### ISSUE TITLE
开头的6个设计原则

### ISSUE THREAD

**Issue by iBotasky** [suzeyu1992/repo#4]
开头的6歌设计原则要是能给几个具体的例子就好了，单纯字面去理解有点困难啊。

**Comment by suzeyu1992** [comment]
嗨, 已经加上了.   [这是地址](http://szysky.com/2016/11/28/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B9%8B%E5%85%AD%E5%A4%A7%E5%8E%9F%E5%88%99%E8%A7%A3%E6%9E%90/)

希望对你有帮助...

**Comment by iBotasky** [comment]
@suzeyu1992 Thanks
